version: '2'
services:
  tribehang-ui:
    container_name: tribehang-ui
    image: tribehang/ui:develop
    mem_limit: 2048m
    volumes:
      - ../ui:/var/www/html
    ports:
      - "80:80"
    build:
      context: ../ui
      dockerfile: Dockerfile
  tribehang-gateway:
    container_name: tribehang-gateway
    image: tribehang/gateway:develop
    mem_limit: 2048m
    env_file:
      - .env
      - .env.develop
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    links:
      - gateway-db
      - redis-db
  gateway-db:
    container_name: gateway-db
    image: mysql:5.7
    volumes:
      - "~/.tribehang-gateway/db:/var/lib/mysql"
      - "./docker/mysql:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  redis-db:
    container_name: redis-db
    image: redis:4.0.6
    volumes:
      - "~/.tribehang-gateway/redis:/data"
    ports:
      - "6379:6379"
